### ISSUE TITLE
darknetImageTest.js -> missing dimensions parameter, wrong length of detections

### ISSUE THREAD

**Issue by b-g** [moovel/node-yolo#11]
If I run `darknetImageTest.js` I get the following output:

```
car: 53%
bicycle: 52%
dog: 56%
1327104 1327104 [ { x: 0.7353335022926331,
    y: 0.2186836153268814,
    w: 0.28237149119377136,
    h: 0.1671832948923111,
    prob: 0.5328023433685303,
    name: 'car' },
  ,
  { x: 0.28434550762176514,
    y: 0.6527453660964966,
    w: 0.2656731605529785,
    h: 0.570385754108429,
    prob: 0.5627787709236145,
    name: 'dog' } ] undefined
```

IMO there are two small issues:
1. the dimensions parameter is `undefined`
2. the length of the detections array is 2 but should be 3. "bicycle" was detected and is missing in detections.

**Comment by OrKoN** [comment]
@b-g do you use the latest version?

**Comment by b-g** [comment]
I think so ... I'm at:
https://github.com/moovel/node-yolo/commit/66a8c67d354e068bb988de6518a7d77cfe9efc81
and
https://github.com/OrKoN/darknet/commit/21ada5d17c5c706c36713a9c630ccdb407103e58

**Comment by OrKoN** [comment]
@b-g did you re-build everything? It works fine for me

```
Loading weights from ./yolo.weights...Done!
region 
car: 53%
bicycle: 52%
dog: 56%
1327104 1327104 [ { x: 0.7353335022926331,
    y: 0.2186836153268814,
    w: 0.28237149119377136,
    h: 0.1671832948923111,
    prob: 0.5328023433685303,
    name: 'car' },
  { x: 0.42732158303260803,
    y: 0.48950856924057007,
    w: 0.5967314839363098,
    h: 0.5472637414932251,
    prob: 0.5157572031021118,
    name: 'bicycle' },
  { x: 0.28434550762176514,
    y: 0.6527453660964966,
    w: 0.2656731605529785,
    h: 0.570385754108429,
    prob: 0.5627787709236145,
    name: 'dog' } ] { width: 768, height: 576 }
```

**Comment by OrKoN** [comment]
The issue you see was fixed by this: https://github.com/moovel/node-yolo/issues/9

**Comment by b-g** [comment]
@OrKoN No :( How can I re-build everything?

**Comment by OrKoN** [comment]
run npm install again, or node-gyp rebuild
Benedikt Groß <notifications@github.com> schrieb am Fr. 24. März 2017 um
15:47:

**Comment by b-g** [comment]
@OrKoN Thanks! That was easy :) `npm install` fixed it! Have a nice weekend!
