### ISSUE TITLE
npm giving error

### ISSUE THREAD

**Issue by AditiBhiwaniwala** [moovel/node-yolo#13]
While executing npm install @moovel/yolo --save , I am getting the error below,

npm ERR! git clone git@github.com:moovel/yolo Cloning into bare repository '/home/aditi/.npm/_git-remotes/git-github-com-moovel-yolo-9b9adb62'...
npm ERR! git clone git@github.com:moovel/yolo Permission denied (publickey).
npm ERR! git clone git@github.com:moovel/yolo fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:moovel/yolo 
npm ERR! git clone git@github.com:moovel/yolo Please make sure you have the correct access rights
npm ERR! git clone git@github.com:moovel/yolo and the repository exists.
npm ERR! addLocal Could not install moovel/yolo
npm ERR! Error: ENOENT, stat 'moovel/yolo'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-80-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "@moovel/yolo"
npm ERR! cwd /home/aditi/Desktop/node/darknet
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path moovel/yolo
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/aditi/Desktop/node/darknet/npm-debug.log
npm ERR! not ok code 0

What can be the reason for it?

**Comment by OrKoN** [comment]
@AditiBhiwaniwala looks like you have outdated node & npm versions. Please use more recent versions like v6.10.2+ (you have 0.10.25) and the npm v3+ (you have 1.3). Let me know if this helps. It seems that the old version of NPM does not support scoped modules (stating with @) as this feature was introduced much later.

**Comment by AditiBhiwaniwala** [comment]
I would appreciate if you could include the proper version of the `node` and `npm` in your `README.md`.  So, that in future people don't face such issues.
Moreover, could you please explain in your `darknet.js` you have included `require('bindings')('darknet')`. So, how exactly you are invoking underlying C++ library function for `node.js`

**Comment by OrKoN** [comment]
The invocation of C/C++ code works as described in the NodeJS documentation: https://nodejs.org/dist/latest-v6.x/docs/api/addons.html Additionally, the module uses https://github.com/nodejs/nan to abstract low-level NodeJS APIs.

**Comment by OrKoN** [comment]
I have added a note about the versions of NodeJS & NPM which the module requires as you suggested. If you have further questions about how native addons work in NodeJS in general, please ask the question on [StackOverflow](https://stackoverflow.com/) because more people will be able to answer.
