### ISSUE TITLE
Car detected as Parking Meter

### ISSUE THREAD

**Issue by AditiBhiwaniwala** [moovel/node-yolo#14]
I am attaching an image in which a car is detected as a parking meter whereas when using the original darknet library the result is correct. If i am using same cfg file, weight file and data file then why is this error coming.

![predictions](https://user-images.githubusercontent.com/21244245/27384933-6a1d09c2-56ae-11e7-9686-994589424436.jpg)

**Comment by OrKoN** [comment]
@AditiBhiwaniwala can you attach the original image? Please note that the fork of darknet we are using is not on par with the current master branch of original darknet. I.e. the latest version of the darknet may produce better/different results.

**Comment by AditiBhiwaniwala** [comment]
![11](https://user-images.githubusercontent.com/21244245/27385418-3fa110c4-56b0-11e7-8112-d8c9de26fca9.jpg)

**Comment by b-g** [comment]
@OrKoN I can't confirm this if I use the image with configs in the `/test` folder ... I get this classifications (w/o the Parking Meter category):

```
[ { x: 0.7554311156272888,
    y: 0.055360980331897736,
    w: 0.07247214019298553,
    h: 0.0692552700638771,
    prob: 0.378817081451416,
    name: 'car' },
  { x: 0.7900861501693726,
    y: 0.041906263679265976,
    w: 0.04912581667304039,
    h: 0.05180671066045761,
    prob: 0.2652934193611145,
    name: 'car' },
  { x: 0.03810616955161095,
    y: 0.17536404728889465,
    w: 0.0602089948952198,
    h: 0.32217973470687866,
    prob: 0.42542749643325806,
    name: 'person' },
  { x: 0.08943124115467072,
    y: 0.16063717007637024,
    w: 0.11497301608324051,
    h: 0.3066703975200653,
    prob: 0.6008384227752686,
    name: 'person' },
  { x: 0.4950035512447357,
    y: 0.43869340419769287,
    w: 0.7062614560127258,
    h: 1.00821053981781,
    prob: 0.7091837525367737,
    name: 'car' } ] 
```
