### ISSUE TITLE
How to change input format?

### ISSUE THREAD

**Issue by AditiBhiwaniwala** [moovel/node-yolo#15]
You have used a 'ImageDetectionWorker' for detecting object in an image in darknet.cc file as:

'class ImageDetectionWorker : public AsyncWorker {
 public:
  ImageDetectionWorker(Callback *callback, InputOptions opts)
    : AsyncWorker(callback), opts(opts) {}'

I want to change the input format of this and i am not understanding where the opts() in the above code comes from. Can you given the reference??

**Comment by OrKoN** [comment]
Hi @AditiBhiwaniwala the options come from here: https://github.com/moovel/node-yolo/blob/master/darknet.cc#L180 and the type is defined here https://github.com/moovel/node-yolo/blob/master/src/types.h#L24

**Comment by OrKoN** [comment]
@AditiBhiwaniwala Was my response helpful? I hope so and, therefore, closing this issue for now

**Comment by AditiBhiwaniwala** [comment]
Yes it helped. Thanks a lot
