### ISSUE TITLE
How to use this wrapper for byte array (of Image) ?

### ISSUE THREAD

**Issue by visha-l** [moovel/node-yolo#16]
I have a byte array of an image which i am extracting from amazon S3 server , can you tell me a way to use this darknet wrapper on byte array , I am using this wrapper for object detection.

**Comment by OrKoN** [comment]
@visha-l the only possibility currently is to store the image to the file system and provide the filename to the library.

**Comment by visha-l** [comment]
But that is taking more time, please tell me if you find some other way to do that, instead of saving it on disk.

**Comment by OrKoN** [comment]
@visha-l I don't think we gonna support this any time soon. But you could mount your S3 as a filesystem (e.g. using https://github.com/s3fs-fuse/s3fs-fuse)
