### ISSUE TITLE
Making a node service using wrapper.

### ISSUE THREAD

**Issue by AditiBhiwaniwala** [moovel/node-yolo#17]
I want to make a node service using your wrapper. I want to initialise the network once and use this network again and again whenever a request come for detection . How can i do this?   

Also there is a lot of memory leak .

**Comment by OrKoN** [comment]
@AditiBhiwaniwala continuous recognition is only supported for video streams - you start it once and the frames are processed till the process shuts down. The single image detection is more like debug/test procedure and is similar what the darknet itself is offering. But you can aways change the logic and split the detectImage call into the setup and detect parts. Please note that detectImage and detect impl. are probably not-thread safe so you will need to test if you can detect several images in parallel. 

And there could be for sure memory leaks. Any PR/test results are helpful!

**Comment by AditiBhiwaniwala** [comment]
So what changes do i need to make in detectImage function so that I can get my desired service.
If i split the detect image function in parts how will my network be available across different calls.

**Comment by OrKoN** [comment]
@AditiBhiwaniwala network is a static variable in c code https://github.com/moovel/node-yolo/blob/master/src/demo.cc#L37 As far as I know, this should be persisted for the entire lifetime of your nodejs process.

**Comment by AditiBhiwaniwala** [comment]
@OrKoN  It worked. Thanks a lot.
