### ISSUE TITLE
Opencv version 3.2.0 not suitable.

### ISSUE THREAD

**Issue by AditiBhiwaniwala** [moovel/node-yolo#18]
I had opencv 3.2.0 in my system but i wasn't able to build this library with it and when i used opencv 3.0.0 it got built. Can you please mention in your documentation the proper version.

Also when I build a server using the network as static the request was processed correct when they were sequential but parallel request created error when running on CPU but were processed correctly when using GPU . Can you tell me what can be the reason?

**Comment by OrKoN** [comment]
@AditiBhiwaniwala Hi, currently the parallel recognition is supported. You need to make sure that you do recognition one-by-one. Also it's a good idea to have a special worker process which does just that and not implement it in the server.

Thanks for the opencv hint. I will add it to the README.
