### ISSUE TITLE
sync OrKoN/darknet with pjreddie/darknet master

### ISSUE THREAD

**Issue by matansag** [moovel/node-yolo#19]
Hi, do you have any plans to sync OrKoN/darknet with pjreddie/darknet master?
and also update node-yolo accordingly?

**Comment by OrKoN** [comment]
Hi @matansag, not at the moment. But eventually yes.

**Comment by OrKoN** [comment]
I hoped that eventually darknet itself will be available as a library so that there is no need in maintaining a fork but it seems this will not happen any time soon.

**Comment by matansag** [comment]
Hi @OrKoN ! 
I understand. 
Don't know if it will help, but i [merged](https://github.com/InSoundz/darknet) your branch with pjreddie/darknet master.
The problem is that some of the function in demo.cc are need to be changed accordingly..
Thanks
Matan

**Comment by OrKoN** [comment]
@matansag do you have any idea how much needs to be changed? Would you mind opening a PR to my fork of darknet with you changes? I will try to test & integrate them soon

**Comment by OrKoN** [comment]
@matansag I have not gone through all the changes in darknet but I opened a PR which seems to be making node-yolo compatible with the darknet version you have. Please give it a try and let me know if you have some problems with it: https://github.com/moovel/node-yolo/pull/20
