### ISSUE TITLE
Saving output as image

### ISSUE THREAD

**Issue by MattCollins84** [moovel/node-yolo#22]
Sorry if this isn't the correct place for this but it is a bit of a niche tool so there's no tmany people discussing this elsewhere!

I have managed to get this working and it's great, except for I can't seem to figure out how to convert the raw output into a useable image file - can someone point me in the right direction?

Thanks!@

**Comment by OrKoN** [comment]
Hi @MattCollins84 

You can convert the raw image to the format you need using ffmpeg. For example, using the command from the test file https://github.com/moovel/node-yolo/blob/master/test/darknetImageTest.js#L12

Best regards,
Alex

**Comment by MattCollins84** [comment]
Ah, I tried this but it didn't work - but now I have it working, I was just being daft I think :)

Is there a good way to turn these converted images into a video?

Thanks for your help

**Comment by OrKoN** [comment]
Yes, you can still do it with ffmpeg: see the video example https://github.com/moovel/node-yolo/blob/master/test/darknetTest.js

**Comment by MattCollins84** [comment]
Thank you very much for your help

**Comment by MattCollins84** [comment]
Hi, just another quick question...

I have the example working (outputting to a video file), but how do I properly stop the creating of the video? At the moment, if I ctrl+c out of my script (the test script), then Quicktime says this video cannot be played. I feel like I am missing something obvious!

**Comment by OrKoN** [comment]
@MattCollins84 for me that works fine, ffmpeg buffers the output and on Ctrl+C it flushes everything to the file. Also programmatically invoking process.exit(0) at the right place (e.g. in the write's callback) worked for me.

**Comment by MattCollins84** [comment]
I have something working now :) I just think that Quicktime player is a bit rubbish - VLC fixes it :)

Thanks
