### ISSUE TITLE
Segmentation fault on Tests

### ISSUE THREAD

**Issue by xhuvom** [moovel/node-yolo#27]
I am running `node darknetTest.js` from test folder after successfully installing darknet and node-yolo bindings as described on Readme. But it gives segmentation fault. My opencv version is 3.3 and node version is v6.11.4

**Comment by OrKoN** [comment]
Hi @xhuvom,

unfortunately, it only works with opencv 2. For example, with 2.4.9.1.

**Comment by xhuvom** [comment]
With opencv 2.4.13, its now working!! Thanks.
