### ISSUE TITLE
Detections object not returning multiples of an object

### ISSUE THREAD

**Issue by nathanmalishev** [moovel/node-yolo#9]
For example if i use a photo containing 2 people the detections object is an array with only one object person parameter, using the detected person with the highest probability. But it still logs that two people were detected.

Is it possible to return the object with all people, their probability & x/y location.

I would be keen to contribute, if you could direct me. Is this a wrapper simply flattening the array or is it an issue with the YOLO build?

**Comment by OrKoN** [comment]
@nathanmalishev Thanks for reporting! I have fixed this issue in https://github.com/moovel/node-yolo/commit/480c02f698e58496468fdb8558ee9259982f0de5 Published as 0.1.8

**Comment by nathanmalishev** [comment]
Thanks for the speedy fix!
